name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            generator: "MinGW Makefiles"
          - os: ubuntu-latest
            generator: "Unix Makefiles"
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: | 
        mkdir build
        cd build
        cmake .. -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=Release
        cmake --build .
