name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            generator: "-G MinGW Makefiles"
          - os: ubuntu-latest
            generator: ""
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: | 
        mkdir build
        cd build
        cmake .. ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=Release
        cmake --build .
