name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            generator: "MinGW Makefiles"
          - os: ubuntu-latest
            generator: "Unix Makefiles"
    env:
      tool: sfc-comp

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Create an archive.
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          mv cmake/bin .
          rm -r cmake
          tar cf - * | xz -z > ${{ env.tool }}.tar.xz
        elif [ "$RUNNER_OS" == "Windows" ]; then
          mv cmake/bin .
          rm -r cmake
          7z a ${{ env.tool }}.7z *
        else
          echo "Not a supported os: $RUNNER_OS"
          exit 1
        fi
